version: '3.8'
services:
  # Docker connection string: postgres://postgres:postgres@localhost:5432/
  db:
    image: postgres
    container_name: travel-test-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: travel_test
      POSTGRES_INITDB_ARGS: '-A md5'
    volumes:
      - travel_db:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  travel_db:
